SET SERVEROUTPUT ON;
SET VERIFY OFF;

DROP TABLE STUDENT_RECORD_SITE1 CASCADE CONSTRAINTS;

CREATE TABLE STUDENT_RECORD_SITE1(
	RECORD_NO NUMBER,
	ID NUMBER,
	NAME VARCHAR2(8),
	QTYPE VARCHAR2(30),
	TOT_QUES NUMBER,
	CORRECTED_QUES NUMBER,
	OBTAINED NUMBER,
	TOT_MARKS NUMBER,
	DATE_EXAM DATE,
	PRIMARY KEY(RECORD_NO)
);

CREATE OR REPLACE TRIGGER RECORED_ADDED
AFTER INSERT
ON STUDENT_RECORD_SITE1
FOR EACH ROW
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('****RESULT ADDED IN RECORD TABLE!****');
END;
/

SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PROCEDURE SAVE_RECORD(SID IN NUMBER,SNAME IN VARCHAR,QUES_TYPE IN VARCHAR,
			TOT_Q IN NUMBER,CORRECTLY_ANSWERED IN VARCHAR,ATTAINED_MARKS IN VARCHAR,TOT_MARKS IN VARCHAR,
			TODAY DATE)
IS
COUNT_ROWS NUMBER;
T NUMBER;
BEGIN

	--DBMS_OUTPUT.PUT_LINE(SID||' '||SNAME||'  '||TODAY||'  '||QUES_TYPE||'  '||TOT_Q||'  '||CORRECTLY_ANSWERED);
	SELECT COUNT(RECORD_NO) INTO COUNT_ROWS FROM STUDENT_RECORD_SITE1;
	COUNT_ROWS:=COUNT_ROWS+3401;
	INSERT INTO STUDENT_RECORD_SITE1 VALUES(COUNT_ROWS,SID,SNAME,QUES_TYPE,TOT_Q,CORRECTLY_ANSWERED,ATTAINED_MARKS,TOT_MARKS,TODAY);
	DELETE FROM TEMP_MEMORY;
	
	IF QUES_TYPE='ALL' THEN
		INSERT INTO STUDENT_RECORD@server1 VALUES(COUNT_ROWS,SID,SNAME,QUES_TYPE,TOT_Q,CORRECTLY_ANSWERED,ATTAINED_MARKS,TOT_MARKS,TODAY);
	END IF;
	
	COMMIT;
	SHOW_ALL_RESULTS;
	
	IF QUES_TYPE='MATHEMATICAL COMPUTATION' THEN
		T:=1;
	ELSIF QUES_TYPE='PERMUTATION AND COMBINATION' THEN
		T:=2;
	ELSIF QUES_TYPE='TRIGONOMETRIC' THEN
		T:=3;
	ELSIF QUES_TYPE='GEOMETRY' THEN
		T:=4;
	ELSE
		T:=5;
	END IF;
	
	SHOW_MERIT(T);
	
END SAVE_RECORD;
/