SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PROCEDURE SHOW_ALL_RESULTS
IS
SD NUMBER;
NOT_FOUND EXCEPTION;
R_NO NUMBER;
BEGIN
	SELECT ID INTO SD FROM CURRENT_RECORD;
	SELECT COUNT(RECORD_NO) INTO R_NO FROM STUDENT_RECORD_SITE1 WHERE ID=SD;
	
	IF R_NO=0 THEN
		RAISE NOT_FOUND;
	ELSE
		DBMS_OUTPUT.PUT_LINE('   YOUR RECORDS:');
		DBMS_OUTPUT.PUT_LINE('++++++++++++++++++++');
		
		DBMS_OUTPUT.PUT_LINE(CHR(10));
		FOR R IN (SELECT * FROM STUDENT_RECORD_SITE1 WHERE ID=SD) LOOP
			DBMS_OUTPUT.PUT_LINE('DATE OF EXAM:    '||R.DATE_EXAM);
			DBMS_OUTPUT.PUT_LINE('*********************************');
			DBMS_OUTPUT.PUT_LINE('QUESTION TYPE:  '||R.QTYPE);
			DBMS_OUTPUT.PUT_LINE('TOTAL QUES:    '||R.TOT_QUES);
			DBMS_OUTPUT.PUT_LINE('CORRECTED ANS:    '||R.CORRECTED_QUES);
			DBMS_OUTPUT.PUT_LINE('OBTAINED MARKS:    '||R.OBTAINED);
			DBMS_OUTPUT.PUT_LINE('TOTAL MARKS:    '||R.TOT_MARKS);
			DBMS_OUTPUT.PUT_LINE('*********************************');
			DBMS_OUTPUT.PUT_LINE(CHR(10));
		END LOOP;
	END IF;
	
	EXCEPTION
		WHEN NOT_FOUND THEN
			DBMS_OUTPUT.PUT_LINE(CHR(10));
			DBMS_OUTPUT.PUT_LINE('****NO TEST HAS NOT YET BEEN GIVEN****');
			DBMS_OUTPUT.PUT_LINE(CHR(10));
END SHOW_ALL_RESULTS;
/