clear screen;

DROP TABLE ANSWERS cascade constraints;
DROP TABLE QUESTIONS cascade constraints;


CREATE TABLE QUESTIONS(
	QID NUMBER,
	QUESTION VARCHAR2(100),
	Q_TYPE VARCHAR2(30),
	DIFFICULTY VARCHAR2(30),
	PRIMARY KEY(QID)
);

CREATE TABLE ANSWERS(
	AID NUMBER,
	QID NUMBER,
	ANSWER VARCHAR2(30),
	PRIMARY KEY(AID),
	FOREIGN KEY(QID) REFERENCES QUESTIONS(QID)
);

INSERT INTO QUESTIONS VALUES(101,'2+9/3*8-8 = ?','MATHEMATICAL COMPUTATION','MEDIUM');
INSERT INTO QUESTIONS VALUES(102,'ln(e)[ln = Natural Logarithm] = ?','MATHEMATICAL COMPUTATION','MEDIUM');
INSERT INTO QUESTIONS VALUES(103,'100/Infinity = ?','MATHEMATICAL COMPUTATION','EASY');
INSERT INTO QUESTIONS VALUES(104,'PI*49/22 [PI=22/7] = ?','MATHEMATICAL COMPUTATION','MEDIUM');
INSERT INTO QUESTIONS VALUES(105,'100011 + 111111 = ? [Both are in BINARY]','MATHEMATICAL COMPUTATION','MEDIUM');
INSERT INTO QUESTIONS VALUES(106,'HOW MANY WAYS 6 PERSONS CAN BE INVITED FOR A PARTY?','PERMUTATION AND COMBINATION','HARD');
INSERT INTO QUESTIONS VALUES(107,'HOW MANY TRIANGLES CAN BE GENERATED FROM A HEXAGON?','PERMUTATION AND COMBINATION','MEDIUM');
INSERT INTO QUESTIONS VALUES(108,'NUMBER OF ORDERS CAN BE GENERATED USING 0..9 (10 DIFFERENT) DIGITS?','PERMUTATION AND COMBINATION','MEDIUM');
INSERT INTO QUESTIONS VALUES(109,'tan(45 deg) = ?','TRIGONOMETRIC','EASY');
INSERT INTO QUESTIONS VALUES(110,'sin2x = ? [FORMULA]','TRIGONOMETRIC','EASY');
INSERT INTO QUESTIONS VALUES(111,'cos(-120 deg)+cos(-60 deg) = ?','TRIGONOMETRIC','MEDIUM');
INSERT INTO QUESTIONS VALUES(112,'tan 20 + tan 25 + tan 20 tan 25 = ?','TRIGONOMETRIC','MEDIUM');
INSERT INTO QUESTIONS VALUES(113,'-1<=cos x<=1? [TRUE(T)/FALSE(F)]','TRIGONOMETRIC','MEDIUM');
INSERT INTO QUESTIONS VALUES(114,'HOW MANY FACTORS CAN BE POSSIBLE FOR 277200?','PERMUTATION AND COMBINATION','HARD');
INSERT INTO QUESTIONS VALUES(115,'HOW MANY WAYS 11 CRICKET PLAYERS CAN BE SELECTED FROM 15 PLAYERS INCLUDING SHAKIB-AL-HASAN?','PERMUTATION AND COMBINATION','HARD');
INSERT INTO QUESTIONS VALUES(116,'RADIUS OF A CIRCLE IS 6cm, WHAT IS THE DIAMETER IN meter?','GEOMETRY','EASY');
INSERT INTO QUESTIONS VALUES(117,'(x1,y1)=(3,4) and (x2,y2)=(6,16), WHAT IS SLOPE?','GEOMETRY','MEDIUM');
INSERT INTO QUESTIONS VALUES(118,'DIAGONALS OF RHOMBUS ARE 2 cm and 3 cm, WHAT IS THE AREA IN cm(square)?','GEOMETRY','MEDIUM');
INSERT INTO QUESTIONS VALUES(119,'A SIDE OF CUBE IS 4 cm , WHAT IS THE SURFACE AREA IN meter(square) = ?','GEOMETRY','MEDIUM');
INSERT INTO QUESTIONS VALUES(120,'BASE = 10 cm and HEIGHT = 15 cm, WHAT IS THE AREA OF TRIANGLE IN cm(square)?','GEOMETRY','EASY');

INSERT INTO ANSWERS VALUES(1001,101,'18');
INSERT INTO ANSWERS VALUES(1002,102,'1');
INSERT INTO ANSWERS VALUES(1003,103,'0');
INSERT INTO ANSWERS VALUES(1004,104,'7');
INSERT INTO ANSWERS VALUES(1005,105,'1100010');
INSERT INTO ANSWERS VALUES(1006,106,'63');
INSERT INTO ANSWERS VALUES(1007,107,'20');
INSERT INTO ANSWERS VALUES(1008,108,'3628800');
INSERT INTO ANSWERS VALUES(1009,109,'1');
INSERT INTO ANSWERS VALUES(1010,110,'2sinxcosx');
INSERT INTO ANSWERS VALUES(1011,111,'0');
INSERT INTO ANSWERS VALUES(1012,112,'1');
INSERT INTO ANSWERS VALUES(1013,113,'T');
INSERT INTO ANSWERS VALUES(1014,114,'179');
INSERT INTO ANSWERS VALUES(1015,115,'1001');
INSERT INTO ANSWERS VALUES(1016,116,'0.12');
INSERT INTO ANSWERS VALUES(1017,117,'4');
INSERT INTO ANSWERS VALUES(1018,118,'3');
INSERT INTO ANSWERS VALUES(1019,119,'0.0096');
INSERT INTO ANSWERS VALUES(1020,120,'75');

COMMIT;
